version: 2.1

orbs:
  slack: circleci/slack@4.2.0

jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - run: echo "Hello World"
      - slack/notify:
          channel: 'dev-notifications'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  send-notification:
    jobs:
      - build:
          context: $SLACK_ACCESS_TOKEN
